FoodValue:
  apple: 2
  baked_potato: -2
  beetroot: 0
  beetroot_soup: 1
  bread: -2
  cake: -1
  carrot: 1
  chorus_fruit: -3
  cooked_chicken: -2
  cooked_cod: -2
  cooked_mutton: -2
  cooked_porkchop: -2
  cooked_rabbit: -2
  cooked_salmon: -2
  cooked_beef: -2
  cookie: -3
  dried_kelp: -5
  golden_apple: -4
  golden_carrot: -4
  honey_bottle: 2
  melon_slice: 5
  milk_bucket: 1
  mushroom_stew: 2
  poisonous_potato: 1
  potato: -2
  potion: 1
  pumpkin_pie: 1
  rabbit_stew: -1
  beef: -2
  chicken: -2
  cod: -2
  mutton: -2
  porkchop: -2
  rabbit: -2
  salmon: -2
  rotten_flesh: -3
  spider_eye: -4
  steak: -2
  suspicious_stew: 1
  sweet_berries: 4